/** 지역 고양이분양 캐터리 사이트 — 서브도메인 = {roman}cat.marketstore.co.kr */

export type CatteryRegion = {
  name: string;
  roman: string;
  slug: string;
  sido: string;
  keyword: string;
  title: string;
  host: string;
  siteUrl: string;
  address: string;
};

const PARENT = "marketstore.co.kr";

/** [지역명, 로마자, 시·도] — slug는 로마자 + cat */
const ROWS: [string, string, string][] = [
  ["화성", "hwaseong", "경기도"],
  ["남양주", "namyangju", "경기도"],
  ["송파", "songpa", "서울특별시"],
  ["인천", "incheon", "인천광역시"],
  ["평택", "pyeongtaek", "경기도"],
  ["강남구", "gangnamgu", "서울특별시"],
  ["김해", "gimhae", "경상남도"],
  ["대구", "daegu", "대구광역시"],
  ["달서구", "dalseogu", "대구광역시"],
  ["시흥", "siheung", "경기도"],
  ["파주", "paju", "경기도"],
  ["노원", "nowon", "서울특별시"],
  ["부평", "bupyeong", "인천광역시"],
  ["덕양구", "deogyanggu", "경기도"],
  ["고양시", "goyang", "경기도"],
  ["제주도", "jejudo", "제주특별자치도"],
  ["제주", "jeju", "제주특별자치도"],
  ["남동구", "namdonggu", "인천광역시"],
  ["김포", "gimpo", "경기도"],
  ["관악구", "gwanakgu", "서울특별시"],
  ["분당", "bundang", "경기도"],
  ["은평구", "eunpyeonggu", "서울특별시"],
  ["강동구", "gangdonggu", "서울특별시"],
  ["성남", "seongnam", "경기도"],
  ["대전", "daejeon", "대전광역시"],
  ["의정부", "uijeongbu", "경기도"],
  ["용인", "yongin", "경기도"],
  ["기흥", "giheung", "경기도"],
  ["양천구", "yangcheongu", "서울특별시"],
  ["성북구", "seongbukgu", "서울특별시"],
  ["광주", "gwangju", "광주광역시"],
  ["미추홀구", "michuholgu", "인천광역시"],
  ["수성구", "suseonggu", "대구광역시"],
  ["서초구", "seochogu", "서울특별시"],
  ["구미", "gumi", "경상북도"],
  ["연수구", "yeonsugu", "인천광역시"],
  ["광산구", "gwangsan", "광주광역시"],
  ["원미구", "wonmigu", "경기도"],
  ["구로구", "gurogu", "서울특별시"],
  ["세종", "sejong", "세종특별자치시"],
  ["중랑구", "jungnanggu", "서울특별시"],
  ["동작구", "dongjakgu", "서울특별시"],
  ["해운대", "haeundae", "부산광역시"],
  ["수지", "suji", "경기도"],
  ["위례", "wirye", "경기도"],
  ["영등포", "yeongdeungpo", "서울특별시"],
  ["유성", "yuseong", "대전광역시"],
  ["마포", "mapo", "서울특별시"],
  ["권선구", "gwonsungu", "경기도"],
  ["영통구", "yeongtonggu", "경기도"],
  ["원주", "wonju", "강원특별자치도"],
  ["양산", "yangsan", "경상남도"],
  ["아산", "asan", "충청남도"],
  ["동대문", "dongdaemun", "서울특별시"],
  ["진주", "jinju", "경상남도"],
  ["광진구", "gwangjingu", "서울특별시"],
  ["상록구", "sangnokgu", "경기도"],
  ["하남", "hanam", "경기도"],
  ["전주", "jeonju", "전북특별자치도"],
  ["안양", "anyang", "경기도"],
  ["동안구", "dongangu", "경기도"],
  ["덕진구", "deokjingu", "전북특별자치도"],
  ["도봉구", "dobonggu", "서울특별시"],
  ["서대문구", "seodaemungu", "서울특별시"],
  ["울산", "ulsan", "울산광역시"],
  ["단원구", "danwongu", "경기도"],
  ["안산", "ansan", "경기도"],
  ["사하구", "sahagu", "부산광역시"],
  ["춘천", "chuncheon", "강원특별자치도"],
  ["강북구", "gangbukgu", "서울특별시"],
  ["계양구", "gyeyanggu", "인천광역시"],
  ["청주", "cheongju", "충청북도"],
  ["양주", "yangju", "경기도"],
  ["광명", "gwangmyeong", "경기도"],
  ["순천", "suncheon", "전라남도"],
  ["성동구", "seongdonggu", "서울특별시"],
  ["장안구", "jangangu", "경기도"],
  ["부산", "busan", "부산광역시"],
  ["여수", "yeosu", "전라남도"],
  ["동래구", "dongnaegu", "부산광역시"],
  ["처인구", "cheoingu", "경기도"],
  ["익산", "iksan", "전북특별자치도"],
  ["경산", "gyeongsan", "경상북도"],
  ["천안", "cheonan", "충청남도"],
  ["군포", "gunpo", "경기도"],
  ["군산", "gunsan", "전북특별자치도"],
  ["경주", "gyeongju", "경상북도"],
  ["성산구", "seongsangu", "경상남도"],
  ["수정구", "sujeonggu", "경기도"],
  ["오산", "osan", "경기도"],
  ["거제", "geoje", "경상남도"],
  ["만안구", "manangu", "경기도"],
  ["소사구", "sosagu", "경기도"],
  ["금천구", "geumcheongu", "서울특별시"],
  ["포항", "pohang", "경상북도"],
  ["이천", "icheon", "경기도"],
  ["울주", "ulju", "울산광역시"],
  ["금정구", "geumjeonggu", "부산광역시"],
  ["목포", "mokpo", "전라남도"],
  ["연제구", "yeonjegu", "부산광역시"],
  ["창원", "changwon", "경상남도"],
  ["의창구", "uichanggu", "경상남도"],
  ["중원구", "jungwongu", "경기도"],
  ["강릉", "gangneung", "강원특별자치도"],
  ["충주", "chungju", "충청북도"],
  ["용산", "yongsan", "서울특별시"],
  ["사상구", "sasanggu", "부산광역시"],
  ["상당구", "sangdanggu", "충청북도"],
  ["팔달구", "paldalgu", "경기도"],
  ["진해", "jinhae", "경상남도"],
  ["청원", "cheongwon", "충청북도"],
  ["구리", "guri", "경기도"],
  ["서원구", "seowongu", "충청북도"],
  ["서귀포", "seogwipo", "제주특별자치도"],
  ["기장", "gijang", "부산광역시"],
  ["서산", "seosan", "충청남도"],
  ["수영구", "suyeonggu", "부산광역시"],
  ["당진", "dangjin", "충청남도"],
  ["대덕구", "daedeokgu", "대전광역시"],
  ["의왕", "uiwang", "경기도"],
  ["안동", "andong", "경상북도"],
  ["광양", "gwangyang", "전라남도"],
  ["포천", "pocheon", "경기도"],
  ["강서구", "gangseogu", "서울특별시"],
  ["강서", "gangseo", "부산광역시"],
  ["종로", "jongno", "서울특별시"],
  ["종로구", "jongnogu", "서울특별시"],
  ["김천", "gimcheon", "경상북도"],
  ["제천", "jecheon", "충청북도"],
  ["양평", "yangpyeong", "경기도"],
  ["통영", "tongyeong", "경상남도"],
  ["나주", "naju", "전라남도"],
  ["여주", "yeoju", "경기도"],
  ["논산", "nonsan", "충청남도"],
  ["사천", "sacheon", "경상남도"],
  ["칠곡", "chilgok", "경상북도"],
  ["영도구", "yeongdogu", "부산광역시"],
  ["정읍", "jeongeup", "전북특별자치도"],
  ["공주", "gongju", "충청남도"],
  ["밀양", "miryang", "경상남도"],
  ["영천", "yeongcheon", "경상북도"],
  ["영주", "yeongju", "경상북도"],
  ["완주", "wanju", "전북특별자치도"],
  ["홍성", "hongseong", "충청남도"],
  ["보령", "boryeong", "충청남도"],
  ["상주", "sangju", "경상북도"],
  ["무안", "muan", "전라남도"],
  ["음성", "eumseong", "충청북도"],
  ["동해", "donghae", "강원특별자치도"],
  ["동두천", "dongducheon", "경기도"],
  ["진천", "jincheon", "충청북도"],
  ["과천", "gwacheon", "경기도"],
  ["속초", "sokcho", "강원특별자치도"],
  ["김제", "gimje", "전북특별자치도"],
  ["예산", "yesan", "충청남도"],
  ["남원", "namwon", "전북특별자치도"],
  ["강화", "ganghwa", "인천광역시"],
  ["문경", "mungyeong", "경상북도"],
  ["홍천", "hongcheon", "강원특별자치도"],
  ["해남", "haenam", "전라남도"],
  ["가평", "gapyeong", "경기도"],
  ["삼척", "samcheok", "강원특별자치도"],
  ["화순", "hwasun", "전라남도"],
  ["고흥", "goheung", "전라남도"],
  ["태안", "taean", "충청남도"],
  ["부여", "buyeo", "충청남도"],
  ["거창", "geochang", "경상남도"],
  ["함안", "haman", "경상남도"],
  ["창녕", "changnyeong", "경상남도"],
  ["예천", "yecheon", "경상북도"],
  ["영암", "yeongam", "전라남도"],
  ["영광", "yeonggwang", "전라남도"],
  ["고창", "gochang", "전북특별자치도"],
  ["금산", "geumsan", "충청남도"],
  ["의성", "uiseong", "경상북도"],
  ["서천", "seocheon", "충청남도"],
  ["고성", "goseong", "경상남도"],
  ["부안", "buan", "전북특별자치도"],
  ["옥천", "okcheon", "충청북도"],
  ["계룡", "gyeryong", "충청남도"],
  ["서울", "seoul", "서울특별시"],
  ["부천", "puchon", "경기도"],
  ["온양", "onyang", "충청남도"],
  ["배곧", "baegot", "경기도"],
  ["마곡", "magok", "서울특별시"],
  ["안성", "anseong", "경기도"],
  ["청라", "cheongna", "인천광역시"],
  ["산본", "sanbon", "경기도"],
  ["동탄", "dongtan", "경기도"],
  ["송탄", "songtan", "경기도"],
  ["연천", "yeoncheon", "경기도"],
  ["태백", "taebaek", "강원특별자치도"],
  ["이태원", "itaewon", "서울특별시"],
  ["홍대", "hongdae", "서울특별시"],
  ["조치원", "jochiwon", "세종특별자치시"],
  ["평창", "pyeongchang", "강원특별자치도"],
  ["송추", "songchu", "경기도"],
  ["미사", "misa", "경기도"],
  ["수원", "suwon", "경기도"],
  ["송도", "songdo", "인천광역시"],
  ["목동", "mokdong", "서울특별시"],
  ["화곡", "hwagok", "서울특별시"],
  ["마산", "masan", "경상남도"],
  ["청양", "cheongyang", "충청남도"],
  ["보은", "boeun", "충청북도"],
  ["영동", "yeongdong", "충청북도"],
  ["무주", "muju", "전북특별자치도"],
  ["진안", "jinan", "전북특별자치도"],
  ["순창", "sunchang", "전북특별자치도"],
  ["담양", "damyang", "전라남도"],
  ["곡성", "gokseong", "전라남도"],
  ["보성", "boseong", "전라남도"],
  ["장흥", "jangheung", "전라남도"],
  ["강진", "gangjin", "전라남도"],
  ["남해", "namhae", "전라남도"],
  ["하동", "hadong", "전라남도"],
  ["구례", "gurye", "전라남도"],
  ["의령", "uiryeong", "경상남도"],
  ["합천", "hapcheon", "경상남도"],
  ["군위", "gunwi", "경상북도"],
  ["영덕", "yeongdeok", "경상북도"],
  ["청송", "cheongsong", "경상북도"],
  ["봉화", "bonghwa", "경상북도"],
  ["영양", "yeongyang", "경상북도"],
  ["울진", "uljin", "경상북도"],
  ["영월", "yeongwol", "강원특별자치도"],
  ["양양", "yangyang", "강원특별자치도"],
  ["인제", "inje", "강원특별자치도"],
  ["화천", "hwacheon", "강원특별자치도"],
  ["철원", "cheorwon", "강원특별자치도"],
];

function toRegion(row: [string, string, string]): CatteryRegion {
  const [name, roman, sido] = row;
  const slug = `${roman}cat`;
  const keyword = `${name}고양이분양`;
  return {
    name,
    roman,
    slug,
    sido,
    keyword,
    title: `${keyword} 전문 캐터리 본점`,
    host: `${slug}.${PARENT}`,
    siteUrl: `https://${slug}.${PARENT}`,
    address: `${sido} ${name} 캐터리본점`,
  };
}

export const CATTERY_REGIONS: CatteryRegion[] = ROWS.map(toRegion);

export const CATTERY_SLUGS = new Set(CATTERY_REGIONS.map((r) => r.slug));

const BY_SLUG = new Map(CATTERY_REGIONS.map((r) => [r.slug, r]));

export function getCatteryRegion(slug: string): CatteryRegion | undefined {
  return BY_SLUG.get((slug || "").toLowerCase().trim());
}

export function isCatterySlug(slug: string): boolean {
  return CATTERY_SLUGS.has((slug || "").toLowerCase().trim());
}

export function catteryHostOf(slug: string): string {
  return `${slug}.${PARENT}`;
}

export const CATTERY_PHONE = "0505-464-1004";
export const CATTERY_PHONE_TEL = "tel:0505-464-1004";
export const CATTERY_HOME = "https://cattery.co.kr";
export const CATTERY_PARENT_HOST = PARENT;
export const CATTERY_THEME = "#1b4d3a";
